### ISSUE TITLE
Add unit/integration tests to each of the ML Pipeline steps

### ISSUE THREAD

**Issue by wujuu** [cyfronet-fid/recommender-system#246]
As the title suggests - tests. Pay special attention to proper fixtures, which could be reused.
Keyword: pytest fixtures

- [x] AE unit/integration tests [@Michal-Kolomanski]
- [ ]  NCF unit/integration tests [@JanKapala]
- [ ]  RL unit/integration tests [@wujuu]
